### ISSUE TITLE
构建工作区报错

### ISSUE THREAD

**Issue by zerosurplus** [ksDreamer/LLM-Robot#1]
您好，请问rosgpt文件中是否缺乏package.xml文件，构建工作区会报错

**Comment by MengyangGao** [comment]
您好，确实缺乏一些ros配置文件，我那时对ros和开源规范还不熟练。正如README里所述，本项目是基于[aniskoubaa的rosgpt](https://github.com/aniskoubaa/rosgpt)结合local llm做的探索，用ros里的turtle控制做了个简单demo。欢迎前往原项目！  我考虑在明年有空时重新构建本项目，做的更加用户友好和模块化。
另外，随着眼界发展，我看到本项目的思路（LLM做规划+Robot执行）已经在很多更优秀的项目中得以体现，不仅是用LLM做简单的规划和指令，也有在传感与感知、可供性/可达性（affordance）、长任务分解、碰撞检测、路径规划等领域作出探索，例如Google提出的Saycan和RT-2，斯坦福大学SVL团队提出的VoxPoser，ReKep等。分享给你～
我将关闭这个issue，如果还有什么疑惑，随时欢迎再次打开！
